[project]
name = "jehoctor-rag-demo"
version = "0.1.0"
description = "Chat with Wikipedia"
readme = "README.md"
authors = [
    { name = "James Hoctor", email = "JEHoctor@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
chat = "rag_demo:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "rag_demo"
